services:
  ozi-postgres:
    volumes:
      - ozi_pgdata_volume:/var/lib/postgresql/data
      - ./init_test_data.sql:/docker-entrypoint-initdb.d/99_init_test_data.sql:ro
      

  ozi-etl:
    build:
      context: ./etl
      dockerfile: Dockerfile.test

  plotly-dash-app:
    ports:
      - "8050:8050"
    restart: "no"

  nginx:
    # Disable nginx for test environment
    # It will not be started when using docker-compose.test.yml
    image: alpine/git # Use a dummy image to prevent starting the actual nginx service
    command: ["tail", "-f", "/dev/null"]
    ports: [] # Ensure no ports are exposed
    networks: [] # Ensure no networks are connected
    depends_on: [] # Ensure no dependencies

volumes:
  ozi_pgdata_volume: