name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to Server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SERVER_HOST: ${{ vars.SERVER_HOST }}
        SSH_USERNAME: ${{ vars.SSH_USERNAME }}
        APP_PATH_ON_SERVER: ${{ vars.APP_PATH_ON_SERVER }}
      run: |
        echo "$SSH_PRIVATE_KEY" > deploy_key.pem
        chmod 600 deploy_key.pem

        ssh -o StrictHostKeyChecking=no -i deploy_key.pem ${SSH_USERNAME}@${SERVER_HOST} << 'EOF'
          cd ${APP_PATH_ON_SERVER}
          git pull origin main
          docker-compose down
          docker-compose up --build -d
        EOF
