name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add SSH Host Key
      env:
        SSH_HOST: ${{ vars.SSH_HOST }}
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${SSH_HOST} >> ~/.ssh/known_hosts
        chmod 600 ~/.ssh/known_hosts

    - name: Deploy to Server
      env:
        SSH_USER: ${{ vars.SSH_USER }}
        SSH_HOST: ${{ vars.SSH_HOST }}
        PROJECT_DIR: /opt/ozi-dashboard
      run: |
        ssh -o StrictHostKeyChecking=no ${SSH_USER}@${SSH_HOST} " \
          cd ${PROJECT_DIR} && \
          git pull && \
          docker compose up -d --build && \
          docker image prune -a -f \
        "
