name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and Run Services
      run: docker-compose up --build -d ozi-postgres ozi-etl

    - name: Wait for Postgres to be healthy
      run: |
        for i in $(seq 1 10); do
          docker-compose exec ozi-postgres pg_isready -U postgres -d db && break
          sleep 5
        done

    - name: Run ETL Tests
      run: docker-compose exec ozi-etl pytest
