name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Create .env.ozi for CI
      run: |
        echo "POSTGRES_USER=postgres" > .env.ozi
        echo "POSTGRES_PASSWORD=password" >> .env.ozi
        echo "POSTGRES_OZI_USER=ozi" >> .env.ozi
        echo "POSTGRES_OZI_PASSWORD=ozi_password" >> .env.ozi
        echo "POSTGRES_DB=db" >> .env.ozi

    - name: Build ETL Production Image
      run: DOCKER_BUILDKIT=0 docker compose build ozi-etl

    - name: Run ETL Tests
      run: DOCKER_BUILDKIT=0 docker compose -f docker-compose.yml -f docker-compose.test.yml run --rm --build --entrypoint "pytest" ozi-etl
